### ISSUE TITLE
WITH is required between CREATE and CALL error

### ISSUE THREAD

**Issue by Analect** [jbarrasa/openpermid2neo4j#1]
@jbarrasa 
I came across your repo while experimenting with openpermids.
I'm trying to import this with the latest version of neo4j (3.3.2) on windows, but hitting this problem with a missing WITH.  Any thoughts on how I might resolve this?

Thanks.
```
c:\neo4j\cypher-shell\cypher-shell> TYPE c:\openPermId\openpermid2neo4j\cypher\rdfImport.cql | cypher-shell.bat -u xxx -p xxx

WITH is required between CREATE and CALL (line 22, column 1 (offset: 847))
"CALL semantics.importRDF("file:///neo4j/neo4j-3.3.2/neo4j-community-3.3.2/import/openPermId/OpenPermID-bulk-organization-20180121_070346.ntriples","N-Triples", {});"
```

![image](https://user-images.githubusercontent.com/4063815/35390109-30e0ca16-01d2-11e8-8fc8-d163daa866ad.png)

**Comment by Analect** [comment]
@jbarrasa 
Sorry for the noise .. I think it was just a case of a missing `;` after the first CREATE statement.  Will close this out.

**Comment by jbarrasa** [comment]
Hi, sorry for the late reply. I was not expecting anyone to use the code yet :)

I've just published the post that goes with it if you want to have a look https://jesusbarrasa.wordpress.com/2018/02/01/neo4j-is-your-rdf-store-part-3-thomson-reuters-openpermid/

Also, curious to hear about your experience.

**Comment by Analect** [comment]
@jbarrasa 
Just seeing this.  Thanks for the link to the blog.  It's really very thorough and I need to go through it step by step!

I ran through your code to import and enrich the data to neo4j ... but I think I must have had neo4j too under-resourced somehow ... although it was on a 32G RAM EC2 machine, it took a whole day!  If you have a fast set-up config that you can share that does these imports and transformations more rapidly, I'd love to see it.

I think your focus up to now has been on enriching the organization and person entities ... I would also be interested in enriching the instruments ... and maybe experimenting with combining data derived from wikidata (have you seen this: https://github.com/thomsonreuters/wikidata_permid_linking).  Ideally, I'm trying to find a way of marrying the openPermId data and LEIs (legal entity identifiers).

Thanks again for your efforts.
